(function(window) {

  // Shared between client & server
  let opcodes = new Object({
    "CLIENT": {
      "REQUEST_LOGIN": {"code": 1, "length": 255},
      "REQUEST_LOGOUT": {"code": 2, "length": 1},
      "MOVE_WEST": {"code": 3, "length": 1},
      "MOVE_NORTH": {"code": 4, "length": 1},
      "MOVE_EAST": {"code": 5, "length": 1},
      "MOVE_SOUTH": {"code": 6, "length": 1},
      "MOVE_NORTHWEST": {"code": 7, "length": 1},
      "MOVE_NORTHEAST": {"code": 8, "length": 1},
      "MOVE_SOUTHEAST": {"code": 9, "length": 1},
      "MOVE_SOUTHWEST": {"code": 10, "length": 1},
      "CLIENT_MESSAGE": {"code": 12, "length": 255},
      "CLIENT_USE_TILE": {"code": 13, "length": 7},
      "CLIENT_MOVE_ITEM": {"code": 16, "length": 13},
      "CONTAINER_CLOSE": {"code": 17, "length": 5},
      "CONTAINER_ITEM_USE": {"code": 20, "length": 6},
      "PLAYER_TURN": {"code": 22, "length": 2},
      "MOVE_ITEM_ALL": {"code": 23, "length": 18},
      "CAST_SPELL": {"code": 24, "length": 3},
      "JOIN_CHANNEL": {"code": 25, "length": 2},
      "SEND_PRIVATE_MESSAGE": {"code": 26, "length": 255},
      "TARGET_CREATURE": {"code": 27, "length": 5},
      "CHANGE_OUTFIT": {"code": 28, "length": 12},
      "LOOK_AT": {"code": 29, "length": 7},
      "ITEM_USE_WITH": {"code": 30, "length": 17},
      "ITEM_USE_ALL": {"code": 31, "length": 9},
      "ITEM_LOOK_ALL": {"code": 32, "length": 9},
      "TARGET_CANCEL": {"code": 33, "length": 1},
      "REMOVE_FRIEND": {"code": 34, "length": 255},
      "ADD_FRIEND": {"code": 35, "length": 255},
      "LEAVE_CHANNEL": {"code": 36, "length": 2},
      "BUY_OFFER": {"code": 37, "length": 7},
      "OPEN_KEYRING": {"code": 38, "length": 1},
      "LATENCY": {"code": 255, "length": 1}
    },
    "SERVER": {
      "ITEM_ADD": {"code": 1, "length": 11},
      "WRITE_CHUNK": {"code": 2, "length": 2049}, 
      "ENTITY_SPAWN": {"code": 3, "length": 11},
      "SERVER_MESSAGE": {"code": 4, "length": 255},
      "CREATURE_MESSAGE": {"code": 5, "length": 255},
      "DECREASE_HEALTH": {"code": 6, "length": 12},
      "ENTITY_MOVE": {"code": 7, "length": 13},
      "OPEN_CONTAINER": {"code": 8, "length": 4096},
      "CONTAINER_ITEM_ADD": {"code": 9, "length": 9},
      "LOGIN_SUCCESS": {"code": 10, "length": 4096},
      "ENTITY_REMOVE": {"code": 11, "length": 5},
      "ITEM_REMOVE": {"code": 12, "length": 9},
      "CREATURE_TURN": {"code": 14, "length": 6},
      "CONTAINER_CLOSE": {"code": 15, "length": 5},
      "CREATURE_INFO": {"code": 16, "length": 255},
      "CONTAINER_ITEM_REMOVE": {"code": 17, "length": 7},
      "SEND_MAGIC_EFFECT": {"code": 18, "length": 8},
      "GAIN_EXPERIENCE": {"code": 19, "length": 7},
      "PLAYER_EQUIP_ITEM": {"code": 20, "length": 5},
      "PLAYER_UNEQUIP_ITEM": {"code": 21, "length": 2},
      "INCREASE_HEALTH": {"code": 22, "length": 7},
      "JOIN_CHANNEL": {"code": 23, "length": 255},
      "CREATURE_TELEPORT": {"code": 24, "length": 11},
      "SEND_PRIVATE_MESSAGE": {"code": 25, "length": 255},
      "LEVEL_ADVANCE": {"code": 26, "length": 1},
      "JOIN_PRIVATE_CHANNEL": {"code": 27, "length": 255},
      "PLAYER_LOGIN": {"code": 28, "length": 255},
      "PLAYER_LOGOUT": {"code": 29, "length": 255},
      "PROPERTY_CHANGE": {"code": 30, "length": 7},
      "SEND_SERVER_DATA": {"code": 32, "length": 255},
      "CHANGE_OUTFIT": {"code": 33, "length": 16},
      "ITEM_INFORMATION": {"code": 34, "length": 255},
      "CANCEL_MESSAGE": {"code": 35, "length": 255},
      "TRANSFORM_ITEM": {"code": 36, "length": 9},
      "SEND_DISTANCE_MAGIC_EFFECT": {"code": 37, "length": 14},
      "FRIEND_STATUS": {"code": 39, "length": 128},
      "REMOVE_FRIEND": {"code": 40, "length": 128},
      "ADD_FRIEND": {"code": 41, "length": 128},
      "CREATURE_SAY": {"code": 42, "length": 4096},
      "READ_TEXT": {"code": 43, "length": 255},
      "CHARACTER_INFORMATION": {"code": 44, "length": 255},
      "ENTER_ZONE": {"code": 45, "length": 255},
      "ADD_ACHIEVEMENT": {"code": 46, "length": 255},
      "TRADE_OFFER": {"code": 47, "length": 4096},
      "WORLD_TIME": {"code": 48, "length": 5},
      "PLAYER_STATISTICS": {"code": 49, "length": 9},
      "COMBAT_LOCK": {"code": 50, "length": 2},
      "SERVER_ERROR": {"code": 51, "length": 255},
      "CAST_SPELL": {"code": 52, "length": 7},
      "WRITE_EMOTE": {"code": 53, "length": 32},
      "TOGGLE_CONDITION": {"code": 54, "length": 8},
      "SET_TARGET": {"code": 55, "length": 5},
      "WRITE_SPELLS": {"code": 56, "length": 255},
      "LATENCY": {"code": 255, "length": 1}
    }
  });

  // Include in NodeJS through require and browser
  if(typeof module === "undefined") {
    window.OPCODES = opcodes;
  } else {
    module.exports = opcodes;
  }

})(this);
